In [2]:
from scipy.interpolate import interp1d
import numpy as np
x = np.arange(10)
y = 2*x + 1
func = interp1d(x, y)
abi = func(np.arange(2.1,3,0.1))
abi


array([5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4, 6.6, 6.8])

In [6]:
#same with univariatespline

from scipy.interpolate import UnivariateSpline
import numpy as np
x = np.arange(10)
y = x**2 +np.sin(x) + 1
func = UnivariateSpline(x, y)
abi = func(np.arange(2.1,3,0.1))
abi

array([5.62826474, 6.03987348, 6.47131994, 6.92265019, 7.3939103 ,
       7.88514634, 8.39640439, 8.92773053, 9.47917082])

In [7]:

##interpolation using radial base functions
from scipy.interpolate import Rbf
import numpy as np
x = np.arange(10)
y = x**2 +np.sin(x) + 1
func = Rbf(x, y)
abi = func(np.arange(2.1,3,0.1))
abi

array([6.25748981, 6.62190817, 7.00310702, 7.40121814, 7.8161443 ,
       8.24773402, 8.69590519, 9.16070828, 9.64233874])