In [7]:
import numpy as np
from scipy.sparse.csgraph import connected_components
from scipy.sparse import csr_matrix
num = np.array([[0,1,2],[1,0,0],[2,0,0]])
newnum = csr_matrix(num)
print(connected_components(newnum))

(1, array([0, 0, 0], dtype=int32))


In [8]:
##dijkstra method to find the shortest path
from scipy.sparse.csgraph import dijkstra
from scipy.sparse import csr_matrix
num = np.array([[0,1,2],[1,0,0],[2,0,0]])
newnum = csr_matrix(num)
print(dijkstra(newnum,return_predecessors=True,indices=0))

(array([0., 1., 2.]), array([-9999,     0,     0], dtype=int32))


In [9]:
#to shortest path using flow warshall method only 2 arguments no indices is needed

from scipy.sparse.csgraph import floyd_warshall
from scipy.sparse import csr_matrix
num = np.array([[0,1,2],[1,0,0],[2,0,0]])
newnum = csr_matrix(num)
print(floyd_warshall(newnum,return_predecessors=True))

(array([[0., 1., 2.],
       [1., 0., 3.],
       [2., 3., 0.]]), array([[-9999,     0,     0],
       [    1, -9999,     0],
       [    2,     0, -9999]], dtype=int32))


In [10]:
##bellman ford method to find the shortest path but it can hancle negative weights

from scipy.sparse.csgraph import bellman_ford
from scipy.sparse import csr_matrix
num = np.array([[0,-1,2],[1,0,0],[2,0,0]])
newnum = csr_matrix(num)
print(bellman_ford(newnum,return_predecessors=True,indices=0))

(array([ 0., -1.,  2.]), array([-9999,     0,     0], dtype=int32))


In [12]:
##depth first order it start from the first node and goes to the last node it takes 2 arg:graph and starting element
from scipy.sparse.csgraph import depth_first_order
from scipy.sparse import csr_matrix
num = np.array([[0,1,0,1],[1,1,1,1],[2,1,1,0],[0,1,0,1]])
newnum = csr_matrix(num)
print(depth_first_order(newnum,1))

(array([1, 0, 3, 2], dtype=int32), array([    1, -9999,     1,     0], dtype=int32))


In [13]:
#breathe first order it returns the breathe from the node it also takes 2 arg:graph and starting element
from scipy.sparse.csgraph import breadth_first_order
from scipy.sparse import csr_matrix
num = np.array([[0,1,0,1],[1,1,1,1],[2,1,1,0],[0,1,0,1]])
newnum = csr_matrix(num)
print(breadth_first_order(newnum,1))

(array([1, 0, 2, 3], dtype=int32), array([    1, -9999,     1,     1], dtype=int32))
