In [4]:

import numpy as np
from scipy.sparse import csr_matrix
num1 = np.array([0,0,0,1,1,0,0,2,2,0,0,6])
print(csr_matrix(num1))


[1 1 2 2 6]


In [5]:
#if we use .data then it will give only the value not the index 
num2 = np.array([0,0,0,1,1,0,0,2,2,0,0,6])
print(csr_matrix(num2).data)

[1 1 2 2 6]


In [7]:
##we can also use it for multi dimensional array
num3 = np.array([[0,0,0,1,1,0],[0,2,2,0,0,6]])
print(csr_matrix(num3).data) 

[1 1 2 2 6]


In [8]:
#suppose we need to count the values only not the zeros means::
num  = np.array([1,0,0,4,0,0,5,0,7,8,0,9,0,0,9,0])
print(csr_matrix(num).count_nonzero())

7


In [13]:
#to eleminate zeros from the array we can use the eliminate_zero() method
num4 = np.array([1,0,0,4,0,0,5,0,7,8,0,9,0,0,9,0])
data = csr_matrix(num4)
data.eliminate_zeros()
print(data)


<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 7 stored elements and shape (1, 16)>
  Coords	Values
  (0, 0)	1
  (0, 3)	4
  (0, 6)	5
  (0, 8)	7
  (0, 9)	8
  (0, 11)	9
  (0, 14)	9


In [17]:
#to remove duplicates from the array we can use the sum_duplicates() method
num = np.array([[1,1,2,0],[2,2,0,0,],[5,5,1,0]])
data = csr_matrix(num)
data.sum_duplicates()
print(data)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 8 stored elements and shape (3, 4)>
  Coords	Values
  (0, 0)	1
  (0, 1)	1
  (0, 2)	2
  (1, 0)	2
  (1, 1)	2
  (2, 0)	5
  (2, 1)	5
  (2, 2)	1


In [18]:
num  = np.array([1,0,0,4,0,0,5,0,7,8,0,9,0,0,9,0])
print(csr_matrix(num).tocsc())

<Compressed Sparse Column sparse matrix of dtype 'int64'
	with 7 stored elements and shape (1, 16)>
  Coords	Values
  (0, 0)	1
  (0, 3)	4
  (0, 6)	5
  (0, 8)	7
  (0, 9)	8
  (0, 11)	9
  (0, 14)	9
